### ISSUE TITLE
(Bug) Error when installing on Fedora 36

### ISSUE THREAD

**Issue by hardBSDk** [markqvist/Sideband#15]
[sideband.log](https://github.com/markqvist/Sideband/files/9874345/sideband.log)

**Comment by markqvist** [comment]
It seems like `pip` can't install `netifaces` via source build.

Can you try installing the `python3-netifaces` and `python3-cryptography` packages with your package manager first? (I forgot what fedora is using for package installs now)

**Comment by hardBSDk** [comment]
@markqvist python3-cryptography is installed by default, python3-netifaces not.

The package names are the same, recommend python3-netifaces before Sideband pip install for Fedora users (or maybe others?).

It worked, thanks.

**Comment by markqvist** [comment]
Yes, I will add this to the docs
