### ISSUE TITLE
Add UDP interface

### ISSUE THREAD

**Issue by buhalo1** [markqvist/Sideband#26]
Since ipv6 has not yet become widespread in primitive home-level local area networks and equipment used in such networks, it would be useful to add the ability to use a UDP interface for communication in such networks.

**Comment by markqvist** [comment]
You don't need any IPv6 setup on your local network for this to work. It will work directly on practically any Ethernet/WiFi network, even without any IP infrastructure (DHCP server, routers, etc) at all.

As long as there is an Ethernet or WiFi carrier, the AutoInterface should work.
