### ISSUE TITLE
latest gps fix may have broken the android repository server.

### ISSUE THREAD

**Issue by michael23505** [markqvist/Sideband#65]
**Describe the Bug**
android repository server will not start

**To Reproduce**
attempt to start the repository server on android in sideband version 1.2.0

**Expected Behavior**
a host ip address and port should show on the repository server page after clicking start repository server

**Logs & Screenshots**
Please include any relevant log output. If applicable, also add screenshots to help explain your problem.

**System Information**
samsung galaxy a52 5g with android 14 and sideband version 1.2.0.

**Comment by markqvist** [comment]
Any error messages show up in the log?

**Comment by markqvist** [comment]
Thanks for reporting this. I've fixed it, and uploaded a new Android APK file to the `1.2.0` release. It is available now.

Could you please try to download it, and verify that it works on your devices?

**Comment by michael23505** [comment]
It works. Thanks again.

**Comment by simplyequipped** [comment]
I'm having this issue again on Sideband 1.30

**Comment by markqvist** [comment]
Can you post the log output with debug logging turned on?

**Comment by simplyequipped** [comment]
Welp, just started up Sideband again to check the log output and it's working fine. Nothing in the log related to the repository server.
